name="VanillaBases";
tooltip="VanillaBases";
overview="5x health for Fence, Watchtower, BarbedWire, BarbedWireLocked, CombinationLock, CombinationLock4, CamoNet.";
picture="VanillaBases/data/picture.paa";
logoSmall="VanillaBases/data/logoSmall.paa";
logo="VanillaBases/data/logo.paa";
logoOver="VanillaBases/data/logo.paa";
action="https://steamcommunity.com/sharedfiles/filedetails/?id=3638007480";
author="moldypenguins";
version="1.1";
